# Components information - azure
---
globalVariables:
  containerPrefix:  "yrn42website-prefix"
  registryLocation: "to-be-replaced"
# TO-SET: registry name must be globally unique
  registryName:     ""
  buildCommand: docker build --rm -f ${env:dockerfile} -t "${env:containerPrefix}/${env:project}:latest" "${env:buildPath}"
  tagCommand: docker tag "${env:containerPrefix}/${env:project}:latest" "${env:registryLocation}/${env:containerPrefix}/${env:project}:latest"
  pushCommand: docker push "${env:registryLocation}/${env:containerPrefix}/${env:project}:latest"

components:
- project: "website"
  buildPath: "frontend/website"
  variables:
